---
title: "Code Style"
author: "Aliaksandr Paulau"
date: "January 22, 2015"
output: html_document
---

### File names
  File names should end in `.R` and be meaningful.
  
### Identifiers
  Don't use underscores (`_`) or hyphens (`-`) in identifiers. The preferred form for variable names is all lower case letters and words separated with dots (`variable.name`), but `variableName` is also accepted; function names have initial capital letters and no dots (`FunctionName`); constants are named like functions but with an initial `k`.
  
### Syntax

#### Line Length
  The maximum line length is 80 characters.
  
#### Indentation
  When indenting your code, use two spaces. Never use tabs or mix tabs and spaces.  
  _Exception: When a line break occurs inside parentheses, align the wrapped line with the first character inside the parenthesis._
  
#### Spacing

Place spaces around all binary operators (`=`, `+`, `-`, `<-`, etc.). 
_Exception: Spaces around `=`'s are optional when passing parameters in a function call._

Do not place a space before a comma, but always place one after a comma.

Place a space before left parenthesis, except in a function call.

Extra spacing (i.e., more than one space in a row) is okay if it improves alignment of equals signs or arrows (`<-`).

Do not place spaces around code in parentheses or square brackets. 
_Exception: Always place a space after a comma._

#### Curly Braces
An opening curly brace should never go on its own line; a closing curly brace should always go on its own line. You may omit curly braces when a block consists of a single statement; however, you must consistently either use or not use curly braces for single statement blocks.

Always begin the body of a block on a new line.

#### Surround else with braces
An else statement should always be surrounded on the same line by curly braces.

#### Assignment
Use `<-`, not `=`, for assignment.

#### Semicolons
Do not terminate your lines with semicolons or use semicolons to put more than one command on the same line. (Semicolons are not necessary, and are omitted for consistency with other Google style guides.)

### Organization

#### General Layout and Ordering
If everyone uses the same general ordering, we'll be able to read and understand each other's scripts faster and more easily.

1. Copyright statement comment
2. Author comment
3. File description comment, including purpose of program, inputs, and outputs `source()` and `library()` statements
4. Function definitions
5. Executed statements, if applicable (e.g., `print`, `plot`)

#### Commenting Guidelines
Comment your code. Entire commented lines should begin with # and one space.

Short comments can be placed after code preceded by two spaces, #, and then one space.

#### Function Definitions and Calls
Function definitions should first list arguments without default values, followed by those with default values.

In both function definitions and function calls, multiple arguments per line are allowed; line breaks are only allowed between assignments.

#### Function Documentation

Functions should contain a comments section immediately below the function definition line. These comments should consist of a one-sentence description of the function; a list of the function's arguments, denoted by `Args:`, with a description of each (including the data type); and a description of the return value, denoted by `Returns:`. The comments should be descriptive enough that a caller can use the function without reading any of the function's code.

##### Example Function
```R
CalculateSampleCovariance <- function(x, y, verbose = TRUE) {
  # Computes the sample covariance between two vectors.
  #
  # Args:
  #   x: One of two vectors whose sample covariance is to be calculated.
  #   y: The other vector. x and y must have the same length, greater than one,
  #      with no missing values.
  #   verbose: If TRUE, prints sample covariance; if not, not. Default is TRUE.
  #
  # Returns:
  #   The sample covariance between x and y.
  n <- length(x)
  # Error handling
  if (n <= 1 || n != length(y)) {
    stop("Arguments x and y have different lengths: ",
         length(x), " and ", length(y), ".")
  }
  if (TRUE %in% is.na(x) || TRUE %in% is.na(y)) {
    stop(" Arguments x and y must not have missing values.")
  }
  covariance <- var(x, y)
  if (verbose)
    cat("Covariance = ", round(covariance, 4), ".\n", sep = "")
  return(covariance)
}
```

#### TODO Style
Use a consistent style for TODOs throughout your code. 
`TODO(username): Explicit description of action to be taken`

### Language

#### Attach
The possibilities for creating errors when using attach are numerous. Avoid it.

#### Functions
Errors should be raised using `stop()`.

#### Objects and Methods

The S language has two object systems, S3 and S4, both of which are available in R. S3 methods are more interactive and flexible, whereas S4 methods are more formal and rigorous. (For an illustration of the two systems, see [Thomas Lumley's "Programmer's Niche: A Simple Class, in S3 and S4" in R News 4/1, 2004, pgs. 33 - 36](http://cran.r-project.org/doc/Rnews/Rnews_2004-1.pdf).)

Use S3 objects and methods unless there is a strong reason to use S4 objects or methods. A primary justification for an S4 object would be to use objects directly in C++ code. A primary justification for an S4 generic/method would be to dispatch on two arguments.

Avoid mixing S3 and S4: S4 methods ignore S3 inheritance and vice-versa.

#### Exceptions

The coding conventions described above should be followed, unless there is good reason to do otherwise. Exceptions include legacy code and modifying third-party code.